@url = http://localhost:8080/api/library/
POST {{url}}bookshelf HTTP/1.1
Content-Type: application/json

{
    "bookshelfName": "Fantasy Worlds with Dragons and Unicorns",
    "type": "Group",
    "libraryId": "d4f1e8c9-3077-4e5f-8c9c-085348044359",
    "parentId": "61526882-7328-11ec-90d6-0242ac120003"

}

###

POST {{url}}book HTTP/1.1
Content-Type: application/json

{
    "isbn": "0426159586",
    "author": "Jane Gaskell",
    "title": "The Dragon",
    "bookshelfId": "615272a0-7328-11ec-90d6-0242ac120003"
   
}

###

PUT {{url}} HTTP/1.1
Content-Type: application/json

{
    "name": "Civil War",
    "bookshelfId": "466e2102-62f2-4b68-ad97-37365b9d3c54",
    "type": "GROUP_SHELF", 
    "libraryId": "61526bb6-7328-11ec-90d6-0242ac120003",
}

###
DELETE {{url}}book HTTP/1.1
Content-Type: application/json

{
  "isbn": "9780618134700",
  "bookshelfId": "615272a0-7328-11ec-90d6-0242ac120003"
}


